CREATE TABLE IF NOT EXISTS hy_audit_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    staff_id VARCHAR(50) NULL,
    actor_name VARCHAR(150) NULL,
    module VARCHAR(100) NOT NULL,
    action_name VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100) NULL,
    entity_id VARCHAR(100) NULL,
    target_label VARCHAR(255) NULL,
    page_url VARCHAR(255) NULL,
    request_method VARCHAR(10) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'success',
    old_values_json LONGTEXT NULL,
    new_values_json LONGTEXT NULL,
    metadata_json LONGTEXT NULL,
    ip_address VARCHAR(45) NULL,
    user_agent VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_hy_audit_logs_staff_id (staff_id),
    KEY idx_hy_audit_logs_module (module),
    KEY idx_hy_audit_logs_action_name (action_name),
    KEY idx_hy_audit_logs_status (status),
    KEY idx_hy_audit_logs_created_at (created_at),
    KEY idx_hy_audit_logs_entity (entity_type, entity_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;